import type { Mc3DReplay } from "@/lib/mc3d/mc3dReplayTypes";

export const AUTHORED_TEST_REPLAY: Mc3DReplay = {
  version: 2,
  durationMs: 7600,
  winner: "left",
  exchanges: [
    {
      id: "exchange_1",
      attacker: "left",
      defender: "right",
      result: "hit",
      phase: "opener",
      timing: {
        startMs: 400,
        approachStartMs: 400,
        windupStartMs: 1150,
        impactMs: 1450,
        recoveryEndMs: 2150,
      },
      leftStartX: -4.6,
      rightStartX: 4.6,
      leftEndX: -0.9,
      rightEndX: 1.7,
      motion: {
        attacker: {
          fromX: -4.6,
          contactX: -0.55,
          settleX: -0.9,
          fromY: 0,
          apexY: 0,
          settleY: 0,
        },
        defender: {
          fromX: 4.6,
          hitX: 0.55,
          settleX: 1.7,
          fromY: 0,
          launchY: 0,
          settleY: 0,
        },
      },
      clips: {
        attackerApproach: "run",
        attackerWindup: "attack",
        attackerRecovery: "idle",
        defenderPreImpact: "idle",
        defenderOnImpact: "hit",
        defenderRecovery: "idle",
      },
      damage: 14,
      defenderHpAfter: 86,
      isLauncher: false,
    },
    {
      id: "exchange_2",
      attacker: "right",
      defender: "left",
      result: "hit",
      phase: "opener",
      timing: {
        startMs: 2550,
        approachStartMs: 2550,
        windupStartMs: 3200,
        impactMs: 3480,
        recoveryEndMs: 4150,
      },
      leftStartX: -1.2,
      rightStartX: 2.3,
      leftEndX: -1.9,
      rightEndX: 0.95,
      motion: {
        attacker: {
          fromX: 2.3,
          contactX: 0.55,
          settleX: 0.95,
          fromY: 0,
          apexY: 0,
          settleY: 0,
        },
        defender: {
          fromX: -1.2,
          hitX: -0.55,
          settleX: -1.9,
          fromY: 0,
          launchY: 0,
          settleY: 0,
        },
      },
      clips: {
        attackerApproach: "run",
        attackerWindup: "attack",
        attackerRecovery: "idle",
        defenderPreImpact: "idle",
        defenderOnImpact: "hit",
        defenderRecovery: "idle",
      },
      damage: 11,
      defenderHpAfter: 89,
      isLauncher: false,
    },
    {
      id: "exchange_3",
      attacker: "left",
      defender: "right",
      result: "hit",
      phase: "pressure",
      timing: {
        startMs: 4550,
        approachStartMs: 4550,
        windupStartMs: 4850,
        impactMs: 5050,
        recoveryEndMs: 5480,
      },
      leftStartX: -1.55,
      rightStartX: 1.15,
      leftEndX: -0.8,
      rightEndX: 1.45,
      motion: {
        attacker: {
          fromX: -1.55,
          contactX: -0.55,
          settleX: -0.8,
          fromY: 0,
          apexY: 0,
          settleY: 0,
        },
        defender: {
          fromX: 1.15,
          hitX: 0.55,
          settleX: 1.45,
          fromY: 0,
          launchY: 0,
          settleY: 0,
        },
      },
      clips: {
        attackerApproach: "idle",
        attackerWindup: "attack",
        attackerRecovery: "idle",
        defenderPreImpact: "idle",
        defenderOnImpact: "hit",
        defenderRecovery: "idle",
      },
      damage: 9,
      defenderHpAfter: 77,
      isLauncher: false,
    },
    {
      id: "exchange_4",
      attacker: "left",
      defender: "right",
      result: "hit",
      phase: "combo_end",
      timing: {
        startMs: 5750,
        approachStartMs: 5750,
        windupStartMs: 6100,
        impactMs: 6350,
        recoveryEndMs: 7050,
      },
      leftStartX: -0.9,
      rightStartX: 1.3,
      leftEndX: -0.65,
      rightEndX: 2.05,
      motion: {
        attacker: {
          fromX: -0.9,
          contactX: -0.55,
          settleX: -0.65,
          fromY: 0,
          apexY: 0,
          settleY: 0,
        },
        defender: {
          fromX: 1.3,
          hitX: 0.55,
          settleX: 2.05,
          fromY: 0,
          launchY: 0.72,
          settleY: 0,
        },
      },
      clips: {
        attackerApproach: "idle",
        attackerWindup: "attack",
        attackerRecovery: "idle",
        defenderPreImpact: "idle",
        defenderOnImpact: "hit",
        defenderRecovery: "idle",
      },
      damage: 22,
      defenderHpAfter: 55,
      isLauncher: true,
    },
  ],
};